sudo: required

language: python

python:
  - 3.6

services:
  - docker

before_install:
  - docker build -t testing-image -f Dockerfile.test .
  - pip install codecov

script:
  - docker run -v $PWD:/data -w /data testing-image ./test-runner.sh

after_success:
  - codecov
