FROM mercury/python-subrepo

ENV INSTALL_DIRECTORY=/tmp

RUN git config --global user.email "example@example.com" \
    && git config --global user.name example

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        rsync \
        unzip \
    && rm -rf /var/lib/apt/lists/*

ADD test_requirements.txt ${INSTALL_DIRECTORY}
ADD requirements.txt ${INSTALL_DIRECTORY}
RUN pip install coverage \
    && pip install -U -r ${INSTALL_DIRECTORY}/test_requirements.txt \
    && pip install -U -r ${INSTALL_DIRECTORY}/requirements.txt
RUN rm ${INSTALL_DIRECTORY}/*requirements.txt
